# Generated by Django 3.2.5 on 2021-11-08 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0002_alter_farm_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NightsNoroeste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpp_s1', models.PositiveSmallIntegerField()),
                ('xaratanga_1', models.PositiveSmallIntegerField()),
                ('ctg_xaratanga', models.PositiveSmallIntegerField()),
                ('porcina_3', models.PositiveSmallIntegerField()),
                ('porcina_4_5', models.PositiveSmallIntegerField()),
                ('tpp_3_0_1', models.PositiveSmallIntegerField()),
                ('tpp_3_0_2', models.PositiveSmallIntegerField()),
                ('tpp_3_0_3', models.PositiveSmallIntegerField()),
                ('tpp_3_0_4', models.PositiveSmallIntegerField()),
                ('tpp_3_0_5', models.PositiveSmallIntegerField()),
                ('xaratanga_s2', models.PositiveSmallIntegerField()),
                ('xaratanga_cmg', models.PositiveSmallIntegerField()),
                ('seccion_10', models.PositiveSmallIntegerField()),
                ('porcina_9', models.PositiveSmallIntegerField()),
                ('laguna_1', models.PositiveSmallIntegerField()),
                ('laguna_2', models.PositiveSmallIntegerField()),
                ('querobabi', models.PositiveSmallIntegerField()),
                ('porcina_6', models.PositiveSmallIntegerField()),
                ('porcina_1', models.PositiveSmallIntegerField()),
                ('seccion_2', models.PositiveSmallIntegerField()),
                ('porcina_2', models.PositiveSmallIntegerField()),
                ('porcina_7', models.PositiveSmallIntegerField()),
                ('luis_emilio', models.PositiveSmallIntegerField()),
                ('maria_emma', models.PositiveSmallIntegerField()),
                ('ludi', models.PositiveSmallIntegerField()),
                ('porcina_10', models.PositiveSmallIntegerField()),
                ('elsa', models.PositiveSmallIntegerField()),
                ('la_palma', models.PositiveSmallIntegerField()),
                ('guaymita', models.PositiveSmallIntegerField()),
                ('xaratanga_3', models.PositiveSmallIntegerField()),
                ('c_mezquite', models.PositiveSmallIntegerField()),
                ('c_obregon', models.PositiveSmallIntegerField()),
                ('c_huatabampo', models.PositiveSmallIntegerField()),
                ('oficina_generales', models.PositiveSmallIntegerField()),
                ('almacen_general', models.PositiveSmallIntegerField()),
                ('planta_alimentos', models.PositiveSmallIntegerField()),
                ('plata_tif_227', models.PositiveSmallIntegerField()),
                ('venta_resaga', models.PositiveSmallIntegerField()),
                ('farm_origen', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='farms.farm')),
            ],
            options={
                'ordering': ('farm_origen',),
            },
        ),
    ]
