# Generated by Django 3.2.5 on 2021-11-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nights_noroeste', '0002_auto_20211108_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='nightsnoroeste',
            name='is_active',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
