# Generated by Django 3.2.5 on 2021-11-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nights_noroeste', '0003_nightsnoroeste_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nightsnoroeste',
            name='is_active',
            field=models.BooleanField(blank=True, default=1, null=True),
        ),
    ]
