# Generated by Django 3.2.5 on 2021-11-21 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nights_noroeste', '0004_alter_nightsnoroeste_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nightsnoroeste',
            options={},
        ),
    ]
