# Generated by Django 3.2.5 on 2022-02-07 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nights_noroeste', '0005_alter_nightsnoroeste_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nightsnoroeste',
            options={'ordering': ('farm_origen__id',)},
        ),
    ]
