# Generated by Django 3.2.5 on 2021-11-08 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0002_alter_farm_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NightsTehuacan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pazoltepec_1a', models.PositiveSmallIntegerField()),
                ('pazoltepec_1b', models.PositiveSmallIntegerField()),
                ('san_luis_1c', models.PositiveSmallIntegerField()),
                ('san_luis_2b', models.PositiveSmallIntegerField()),
                ('cacaluapan_2c', models.PositiveSmallIntegerField()),
                ('cuarentena_mora', models.PositiveSmallIntegerField()),
                ('san_luis_3b', models.PositiveSmallIntegerField()),
                ('cacaluapan_3c', models.PositiveSmallIntegerField()),
                ('tepanco_3a', models.PositiveSmallIntegerField()),
                ('tepanco_3b', models.PositiveSmallIntegerField()),
                ('tepanco_3c', models.PositiveSmallIntegerField()),
                ('recria_san_bartolo', models.PositiveSmallIntegerField()),
                ('oficina_generales', models.PositiveSmallIntegerField()),
                ('almacen_general', models.PositiveSmallIntegerField()),
                ('planta_alimentos', models.PositiveSmallIntegerField()),
                ('farm_origen', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='farms.farm')),
            ],
        ),
    ]
