# Generated by Django 3.2.5 on 2021-11-09 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nights_tehuacan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nightstehuacan',
            name='almacen_general',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='nightstehuacan',
            name='cacaluapan_2c',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='nightstehuacan',
            name='cacaluapan_3c',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='nightstehuacan',
            name='cuarentena_mora',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='nightstehuacan',
            name='oficina_generales',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='nightstehuacan',
            name='pazoltepec_1a',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='nightstehuacan',
            name='pazoltepec_1b',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='nightstehuacan',
            name='planta_alimentos',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='nightstehuacan',
            name='recria_san_bartolo',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='nightstehuacan',
            name='san_luis_1c',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='nightstehuacan',
            name='san_luis_2b',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='nightstehuacan',
            name='san_luis_3b',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='nightstehuacan',
            name='tepanco_3a',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='nightstehuacan',
            name='tepanco_3b',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='nightstehuacan',
            name='tepanco_3c',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
