# Generated by Django 3.2.5 on 2021-11-25 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('status_authorization', '0001_initial'),
        ('farms', '0008_remove_farm_quarantine_nights'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('nights', models.PositiveSmallIntegerField()),
                ('reason', models.TextField(max_length=255)),
                ('is_authorized', models.BooleanField(default=False)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farms.farm')),
                ('status_aut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='status_authorization.statusauthorization')),
                ('user_auth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_auth', to=settings.AUTH_USER_MODEL)),
                ('user_sol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_sol', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
