# Generated by Django 3.2.5 on 2021-11-26 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_visit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulevisit',
            name='number_of_people',
            field=models.PositiveSmallIntegerField(default=3),
            preserve_default=False,
        ),
    ]
