# Generated by Django 3.2.5 on 2021-11-09 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nights_veracruz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nightsveracruz',
            name='almacen_general',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='nightsveracruz',
            name='angelito',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='nightsveracruz',
            name='capulines_1',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='nightsveracruz',
            name='capulines_2',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='nightsveracruz',
            name='capulines_rentado',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='nightsveracruz',
            name='copital',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='nightsveracruz',
            name='cruz',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='nightsveracruz',
            name='cuarentena',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='nightsveracruz',
            name='cuarentena_lupita',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='nightsveracruz',
            name='gertrudis',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='nightsveracruz',
            name='gloria',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='nightsveracruz',
            name='gregorio',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='nightsveracruz',
            name='iguazu',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='nightsveracruz',
            name='mata_espino',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='nightsveracruz',
            name='milagro',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='nightsveracruz',
            name='oficina_angelito',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='nightsveracruz',
            name='palomas',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='nightsveracruz',
            name='planta_alimentos',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='nightsveracruz',
            name='venta_deposito',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
