# Generated by Django 3.2.5 on 2021-11-16 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nights_veracruz', '0002_auto_20211108_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nightsveracruz',
            options={'ordering': ('farm_origen',)},
        ),
    ]
