# Generated by Django 3.2.5 on 2021-11-09 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nights_regiones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nightsregiones',
            name='cordoba',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='nightsregiones',
            name='noroeste',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='nightsregiones',
            name='tehuacan',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='nightsregiones',
            name='veracruz',
            field=models.PositiveSmallIntegerField(default=4),
        ),
    ]
