# Generated by Django 3.2.5 on 2021-11-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
