# Generated by Django 3.2.5 on 2021-11-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_alter_farm_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='farm_restriction',
            field=models.JSONField(default=dict),
        ),
    ]
