# Generated by Django 3.2.5 on 2021-11-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0005_alter_farm_quarantine_nights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='quarantine_nights',
            field=models.JSONField(default=[{'noches': ['0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0']}]),
        ),
    ]
