# Generated by Django 3.2.5 on 2021-11-22 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farms', '0008_remove_farm_quarantine_nights'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitedFarmByUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_date', models.DateTimeField(auto_now_add=True)),
                ('acutal_date', models.DateTimeField(auto_now_add=True)),
                ('is_same_flow', models.BooleanField(default=False)),
                ('nights', models.PositiveSmallIntegerField(default=0)),
                ('reason', models.CharField(max_length=250, null=True)),
                ('actual_farm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actul_farm', to='farms.farm')),
                ('previous_farm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_farm', to='farms.farm')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
