# Generated by Django 3.2.5 on 2021-11-22 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitedfarmbyuser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitedfarmbyuser',
            old_name='acutal_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='visitedfarmbyuser',
            name='previous_date',
        ),
    ]
