# Generated by Django 3.2.5 on 2021-11-22 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0008_remove_farm_quarantine_nights'),
        ('visitedfarmbyuser', '0002_auto_20211122_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitedfarmbyuser',
            name='actual_farm',
        ),
        migrations.RemoveField(
            model_name='visitedfarmbyuser',
            name='previous_farm',
        ),
        migrations.AddField(
            model_name='visitedfarmbyuser',
            name='destination_farm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_farm', to='farms.farm'),
        ),
        migrations.AddField(
            model_name='visitedfarmbyuser',
            name='origin_farm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_farm', to='farms.farm'),
        ),
        migrations.AlterField(
            model_name='visitedfarmbyuser',
            name='reason',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
