# Generated by Django 3.2.5 on 2021-11-23 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visitedfarmbyuser', '0003_auto_20211122_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitedfarmbyuser',
            name='authorizing_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorizing_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitedfarmbyuser',
            name='is_authorized',
            field=models.BooleanField(default=False),
        ),
    ]
