# Generated by Django 3.2.5 on 2021-11-26 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitedfarmbyuser', '0004_auto_20211123_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitedfarmbyuser',
            name='number_of_people',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
