# Generated by Django 3.2.5 on 2021-12-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitedfarmbyuser', '0006_alter_visitedfarmbyuser_number_of_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitedfarmbyuser',
            name='names_of_people',
            field=models.TextField(blank=True),
        ),
    ]
